### ISSUE TITLE
Rescaled parts

### ISSUE THREAD

**Issue by yalov** [KSPSnark/MissingHistory#2]
JanitorCloset can't filter rescaled parts

Craft Manager can't find rescaled parts on KerbalX
https://i.imgur.com/qocBcNf.png

Maybe make it "separate" parts? copy from stock folder, not scale stock parts?

**Comment by KSPSnark** [comment]
No, rescaled stock parts are how it works.  Not least because **copying stock artwork is illegal**-- those are assets that are owned by Squad and aren't freely copyable.  What I've done, on the other hand, is perfectly reasonable:  the mod simply adds a _reference_ to the stock parts, which is simple, efficient, cheap in terms of resources, and (most importantly) legal.

So, the current behavior here is as designed.  Rescaling parts and giving them new names via ModuleManager is a not uncommon thing to do-- MissingHistory is hardly the first mod to do something like that.  If other mods (such as JanitorCloset) have trouble with that, then that's an issue there.

**Comment by Ruedii** [comment]
There is an option Bulkhead profile that can be added to provide classification by size.  This at least works on the stock categorization by bulkhead profile.  I'm not sure if it works on JanitorCloset, though.
